import type { Product, Review } from '../types';
import { CATEGORIES } from './categories';
import { slugify } from '../lib/slugify';

const cat = (slug: string) => CATEGORIES.find((c) => c.slug === slug)!.id;

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/1000`;

const RAW_MOCK_PRODUCTS: Omit<Product, 'slug' | 'notify_on_publish' | 'is_active' | 'affiliate_commission_rate'>[] = [
  {
    id: 'p-costume-01',
    category_id: cat('costumes'),
    name: 'Costume Croisé Anthracite',
    description:
      "Costume trois pièces en laine peignée, coupe cintrée. Doublure satinée, revers cranté. L'allure de référence pour vos occasions les plus importantes.",
    price: 185000,
    compare_at_price: 235000,
    images: [img('costume1a'), img('costume1b'), img('costume1c')],
    colors: ['Anthracite', 'Bleu Marine', 'Noir'],
    sizes: ['48', '50', '52', '54', '56'],
    stock: 12,
    is_flash_sale: true,
    flash_sale_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    rating: 4.8,
    review_count: 24,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-costume-02',
    category_id: cat('costumes'),
    name: 'Costume Slim Bleu Nuit',
    description: 'Coupe slim moderne, tissu extensible quatre saisons, finitions main.',
    price: 165000,
    compare_at_price: null,
    images: [img('costume2a'), img('costume2b')],
    colors: ['Bleu Nuit', 'Gris'],
    sizes: ['46', '48', '50', '52'],
    stock: 8,
    is_flash_sale: false,
    flash_sale_ends_at: null,
    rating: 4.6,
    review_count: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-chemise-01',
    category_id: cat('chemises'),
    name: 'Chemise Oxford Blanche',
    description: 'Coton égyptien, col italien, coupe ajustée. Un essentiel intemporel.',
    price: 42000,
    compare_at_price: 55000,
    images: [img('chemise1a'), img('chemise1b')],
    colors: ['Blanc', 'Bleu Ciel'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 30,
    is_flash_sale: true,
    flash_sale_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    rating: 4.7,
    review_count: 41,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-chemise-02',
    category_id: cat('chemises'),
    name: 'Chemise à Rayures Fines',
    description: 'Popeline légère, motif rayé discret, idéale sous costume ou seule.',
    price: 38000,
    compare_at_price: null,
    images: [img('chemise2a'), img('chemise2b')],
    colors: ['Bleu/Blanc', 'Gris/Blanc'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 20,
    is_flash_sale: false,
    flash_sale_ends_at: null,
    rating: 4.4,
    review_count: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-cravate-01',
    category_id: cat('cravates'),
    name: 'Cravate Soie Bordeaux',
    description: '100% soie tissée, motif chevron discret. Nœud impeccable garanti.',
    price: 22000,
    compare_at_price: 28000,
    images: [img('cravate1a')],
    colors: ['Bordeaux', 'Or', 'Noir'],
    sizes: ['Taille unique'],
    stock: 25,
    is_flash_sale: true,
    flash_sale_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    rating: 4.9,
    review_count: 33,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-chaussure-01',
    category_id: cat('chaussures'),
    name: 'Derby Cuir Noir',
    description: "Cuir pleine fleur, semelle Goodyear, fabrication artisanale.",
    price: 95000,
    compare_at_price: null,
    images: [img('chaussure1a'), img('chaussure1b')],
    colors: ['Noir', 'Marron'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    stock: 14,
    is_flash_sale: false,
    flash_sale_ends_at: null,
    rating: 4.7,
    review_count: 19,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-montre-01',
    category_id: cat('montres'),
    name: 'Montre Chronographe Or',
    description: 'Boîtier acier plaqué or, bracelet cuir, mouvement quartz précis.',
    price: 145000,
    compare_at_price: 180000,
    images: [img('montre1a'), img('montre1b')],
    colors: ['Or', 'Argent'],
    sizes: ['Taille unique'],
    stock: 6,
    is_flash_sale: true,
    flash_sale_ends_at: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    rating: 5.0,
    review_count: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-accessoire-01',
    category_id: cat('accessoires'),
    name: 'Ceinture Cuir Boucle Or',
    description: 'Cuir pleine fleur italien, boucle plaquée or brossé.',
    price: 32000,
    compare_at_price: null,
    images: [img('accessoire1a')],
    colors: ['Noir', 'Marron'],
    sizes: ['90cm', '95cm', '100cm', '105cm'],
    stock: 18,
    is_flash_sale: false,
    flash_sale_ends_at: null,
    rating: 4.5,
    review_count: 7,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = RAW_MOCK_PRODUCTS.map((p) => ({
  ...p,
  slug: slugify(p.name),
  notify_on_publish: true,
  is_active: true,
  affiliate_commission_rate: null,
}));

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    product_id: 'p-costume-01',
    user_id: 'u1',
    author_name: 'Idriss M.',
    rating: 5,
    comment: 'Coupe parfaite, qualité au rendez-vous. Livraison rapide à N\'Djamena.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'r2',
    product_id: 'p-costume-01',
    user_id: 'u2',
    author_name: 'Ahmat K.',
    rating: 4,
    comment: 'Très beau tissu, juste la manche un peu longue.',
    created_at: new Date().toISOString(),
  },
];
