export type RootStackParamList = {
  Tabs: undefined;
  Category: { slug: string };
  Product: { slug: string };
  Checkout: undefined;
  Orders: undefined;
  Travel: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  ResetPassword: undefined;
  AdminProducts: undefined;
  AdminProductForm: { productId?: string };
  AdminOrders: undefined;
  AdminTravelRequests: undefined;
  AdminCategories: undefined;
  AdminPaymentSettings: undefined;
  AdminCustomers: undefined;
  AdminCustomerDetail: { userId: string };
  AdminDashboard: undefined;
  AdminSourcePerformance: undefined;
  AdminAbandonedCarts: undefined;
  AdminNotifications: undefined;
  AdminPromotions: undefined;
  AdminStoreSettings: undefined;
  Contact: undefined;
  CustomerNotifications: undefined;
  NotificationSettings: undefined;
  Favorites: undefined;
  AdminCities: undefined;
  PrivacyPolicy: undefined;
  ReturnPolicy: undefined;
  Messages: undefined;
  AdminMessages: undefined;
  AffiliateApply: undefined;
  AffiliateDashboard: undefined;
  AffiliateProducts: undefined;
  AdminAffiliates: undefined;
  AdminAffiliateSettings: undefined;
  AdminAffiliateCommissions: undefined;
  OrderConfirmation: { orderId: string; total: number; instructions: string | null };
  AdminBestLeads: undefined;
  Wheel: undefined;
  AdminWheel: undefined;
};

export type TabParamList = {
  Home: undefined;
  Search: undefined;
  Cart: undefined;
  Account: undefined;
};
